DjangoHerokuSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^psnvalue/', include('psnvalue.urls')),
]

psnvalue/urls.py
from django.conf.urls import url

from . import views

app_name = 'psnvalue'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<library_id>[0-9]+)/gamelist/$', views.GameListView.as_view(), name='gamelist'),
    url(r'^(?P<library_id>[0-9]+)/updatelib/$', views.view_sync_psn_library_with_psn_store, name='updatelib'),
    url(r'^(?P<library_id>[0-9]+)/updateweightedrating/$', views.view_update_psn_weighted_ratings, name='updateweightedrating'),
    url(r'^(?P<library_id>[0-9]+)/updategamethumbs/$', views.view_update_psn_game_thumbnails, name='updategamethumbs'),
]

psnvalue/models.py
import datetime

from django.db import models
from django.utils import timezone

def last_day_timedate():
    return timezone.now() - datetime.timedelta(days=1)

class Library(models.Model):
    library_name = models.TextField(unique=True)
    last_updated = models.DateTimeField(default=timezone.now)
    library_url = models.TextField()
    library_rating_stdev = models.FloatField(default=0.0)
    library_rating_mean = models.FloatField(default=0.0)

    def __str__(self):
        return self.library_name

    def was_updated_within_last_day(self):
        return self.last_updated >= last_day_timedate()

class GameList(models.Model):
    game_id = models.TextField(unique=True)
    game_name = models.TextField()
    json_url = models.TextField()
    age_rating = models.IntegerField(default=0)
    library_fk = models.ForeignKey(Library, on_delete=models.CASCADE)
    last_updated = models.DateTimeField(default=timezone.now)
    # Thumbnail fields
    image_url = models.TextField()
    image_datastore_url = models.TextField(blank=True)
    # Price fields
    price = models.FloatField(default=0.0)
    base_price = models.FloatField(default=0.0)
    plus_price = models.FloatField(default=0.0)
    base_discount = models.IntegerField(default=0)
    plus_discount = models.IntegerField(default=0)
    # Rating fields
    rating = models.FloatField(default=0.0)
    rating_count = models.IntegerField(default=0)
    weighted_rating = models.FloatField(default=0.0)
    # Value fields
    base_value_score = models.IntegerField(default=0)
    plus_value_score = models.IntegerField(default=0)

    def __str__(self):
        return self.game_id + ": " + self.game_name

    def was_updated_within_last_day(self):
        return self.last_updated >= last_day_timedate()

class ContentDescriptors(models.Model):
    content_name = models.TextField(unique=True)
    content_description = models.TextField()

    def __str__(self):
        return self.content_name

class GameContent(models.Model):
    game_id_fk = models.ForeignKey(GameList, on_delete=models.CASCADE)
    content_descriptor_fk = models.ForeignKey(ContentDescriptors, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('game_id_fk', 'content_descriptor_fk',)

DjangoHerokuSite/views.py
from django.shortcuts import render

def index(request):
    template_name = 'DjangoHerokuSite/index.html'
    return render(request, template_name, None)

psnvalue/views.py
from django.views import generic
from django.http import HttpResponse
from django.http import Http404

from .models import Library, GameList
from .tasks import task_sync_psn_library_with_psn_store, task_update_psn_weighted_ratings, task_update_psn_game_thumbnails

# Library homepage for admin user.
INDEX_TEMPLATE_ADMIN = 'psnvalue/index_admin.html'
# Library homepage for regular user.
INDEX_TEMPLATE_USER = 'psnvalue/index.html'
# Context object name for library list - used in the HTML.
INDEX_CON = 'library_list'

# Game list template page
GAMELIST_TEMPLATE = 'psnvalue/gamelist.html'
# Context object name for game list - used in the HTML.
GAMELIST_CON = 'game_list'
# The number of games to display on each page of results.
GAMELIST_GAMES_PER_PAGE = 40
# The minimum number of ratings needed by a game to be displayed.
GAMELIST_MIN_RATING_COUNT = 50
# The minimum price of a game to be displayed (used to exclude free to play).
GAMELIST_MIN_PRICE = 1
# The parameter name for the library id to display games for.
GAMELIST_LIBRARY_ID_PARAM = 'library_id'
# The ordering of results for the game list.
GAMELIST_ORDER_BY = '-plus_value_score'

class IndexView(generic.ListView):
    """
    Game library homepage view.

    Displays the list of game libraries and the date of last update for each library. If the admin
    user is logged in, a link will be displayed to allow for a manual update of a library.
    """
    context_object_name = INDEX_CON

    def get_template_names(self):
        """
        Return the game library home page for regular and admin users.
        """
        if self.request.user.is_staff:
            return [INDEX_TEMPLATE_ADMIN]
        else:
            return [INDEX_TEMPLATE_USER]

    def get_queryset(self):
        """
        Get all librarys from the database.
        """
        return Library.objects.all()

class GameListView(generic.ListView):
    """
    Game list view.

    View used for displaying the list of games, and their details, from the library. Results are paginated.
    """
    template_name = GAMELIST_TEMPLATE
    context_object_name = GAMELIST_CON
    paginate_by = GAMELIST_GAMES_PER_PAGE

    def get_queryset(self):
        """
        Get ordered and filtered list of Games.

        Filter games based on library id, count of ratings and price. Order by PS Plus value score.
        """
        return GameList.objects.filter(library_fk=self.kwargs[GAMELIST_LIBRARY_ID_PARAM], rating_count__gte=GAMELIST_MIN_RATING_COUNT, price__gte=GAMELIST_MIN_PRICE).order_by(GAMELIST_ORDER_BY)

def view_sync_psn_library_with_psn_store(request, library_id):
    """
    View used for syncing the local PSN library with the PSN store.

    This update is performed asynchronously by utilisng a celery task.
    Update can only be triggered through this view by an admin user.

    Args:
        request: The HTTP request
        library_id: The ID of the local library to update.
    Returns:
        The HTTP response.
    """
    if not request.user.is_staff:
        raise Http404("You do not have access to this resource.")
    task_sync_psn_library_with_psn_store.delay(library_id)
    return HttpResponse("You're at the psnvalue updatelib.")

def view_update_psn_weighted_ratings(request, library_id):
    """
    View used for updating the weighted rating for each PSN game in the library.

    This update is performed asynchronously by utilisng a celery task.
    Update can only be triggered through this view by an admin user.

    Args:
        request: The HTTP request
        library_id: The ID of the local libray whose games we want to update.
    Returns:
        The HTTP response.
    """
    if not request.user.is_staff:
        raise Http404("You do not have access to this resource.")
    task_update_psn_weighted_ratings.delay(library_id)
    return HttpResponse("You're at the psnvalue update weighted rating.")

def view_update_psn_game_thumbnails(request, library_id):
    """
    View used for updating the stored PSN game thumbnails.

    Can be used if the thumbnail storage location is changed.

    This update is performed asynchronously by utilisng a celery task.
    Update can only be triggered through this view by an admin user.

    Args:
        request: The HTTP request
        library_id: The ID of the local libray whose games we want to update.
    Returns:
        The HTTP response.
    """
    if not request.user.is_staff:
        raise Http404("You do not have access to this resource.")
    task_update_psn_game_thumbnails.delay(library_id)
    return HttpResponse("You're at the psnvalue update game thumbs.")

DjangoHerokuSite/templates/DjangoHerokuSite/index.html
<p>Home Page</p>
<ul>
    <li><a href="/psnvalue/1/gamelist">List of PSN Games by Value</a></li>
</ul>

psnvalue/templates/psnvalue/gamelist.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'psnvalue/style.css' %}" />

{% if game_list %}
    <table>
        <tr>
            <th>Game Cover</th>
            <th>Game Name</th>
            <th>Game Rating</th>
            <th>Game Price</th>
            <th>Game Value</th>
        </tr>
        {% for game in game_list %}
        <tr>
            <td><img src="{{ game.image_datastore_url }}" height="80" width="80"/></td>
            <td>{{ game.game_name }}</td>
            <td>{{ game.weighted_rating }}</td>
            <td>{{ game.plus_price }}</td>
            {% if True %}
            <td>{{ game.plus_value_score }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No games are available.</p>
{% endif %}

{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

psnvalue/templates/psnvalue/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'psnvalue/style.css' %}" />

{% if library_list %}
    <ul>
    {% for library in library_list %}
       <li><a href="{% url 'psnvalue:gamelist' library.id %}">{{ library.library_name }}</a> --- Last Updated: {{ library.last_updated }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No game libraries are available.</p>
{% endif %}

psnvalue/templates/psnvalue/index_admin.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'psnvalue/style.css' %}" />

{% if library_list %}
    <ul>
    {% for library in library_list %}
       <li><a href="{% url 'psnvalue:gamelist' library.id %}">{{ library.library_name }}</a> --- Last Updated: {{ library.last_updated }} --- (<a href="{% url 'psnvalue:updatelib' library.id %}">Update</a>)</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No game libraries are available.</p>
{% endif %}